In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(5,3),index=["a","c","e","f","h"],columns=["one","two","three"])
df=df.reindex(["a","b","c","d","e","f","g","h"])
print(df["one"].isnull())

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool

In [ ]:
print(df)

        one       two     three
a -0.597427 -0.852301  1.097874
b       NaN       NaN       NaN
c -1.956554 -0.204815 -1.472629
d       NaN       NaN       NaN
e -0.453059 -0.409941 -0.563738
f  0.212223  1.070958 -0.047738
g       NaN       NaN       NaN
h  0.228328  0.287369  1.828296

In [ ]:
print("NaN replaced with'0':")
print(df.fillna(0))

NaN replaced with'0':
        one       two     three
a -0.597427 -0.852301  1.097874
b  0.000000  0.000000  0.000000
c -1.956554 -0.204815 -1.472629
d  0.000000  0.000000  0.000000
e -0.453059 -0.409941 -0.563738
f  0.212223  1.070958 -0.047738
g  0.000000  0.000000  0.000000
h  0.228328  0.287369  1.828296

In [ ]:
print(df)
print("-------------------------------")
print(df.fillna(method="pad"))

        one       two     three
a -0.597427 -0.852301  1.097874
b       NaN       NaN       NaN
c -1.956554 -0.204815 -1.472629
d       NaN       NaN       NaN
e -0.453059 -0.409941 -0.563738
f  0.212223  1.070958 -0.047738
g       NaN       NaN       NaN
h  0.228328  0.287369  1.828296
-------------------------------
        one       two     three
a -0.597427 -0.852301  1.097874
b -0.597427 -0.852301  1.097874
c -1.956554 -0.204815 -1.472629
d -1.956554 -0.204815 -1.472629
e -0.453059 -0.409941 -0.563738
f  0.212223  1.070958 -0.047738
g  0.212223  1.070958 -0.047738
h  0.228328  0.287369  1.828296

In [ ]:
df = pd.DataFrame(np.random.randn(5,3),index=["a","c","e","f","h"],columns=["one","two","three"])
df=df.reindex(["a","b","c","d","e","f","g","h"])
print(df.fillna(method="bfill"))

        one       two     three
a -0.262162  1.606241 -0.239464
b  0.467039  0.967971 -0.966213
c  0.467039  0.967971 -0.966213
d  0.427327  0.081098  0.184902
e  0.427327  0.081098  0.184902
f  1.274831 -0.752684  2.132642
g -1.431050 -0.342060  0.023845
h -1.431050 -0.342060  0.023845

In [ ]:
import numpy as np
df = pd.DataFrame(np.random.randn(5,3),index=["a","c","e","f","h"],columns=["one","two","three"])
print(df)
df=df.reindex(["a","b","c","d","e","f","g","h"])
print(df)
print(df.dropna())

        one       two     three
a  0.437957  0.100567 -1.568301
c  0.082134  1.475826  2.258137
e -1.009481  1.258612  0.714542
f -0.919802 -2.616542  0.396808
h -0.073464  1.252943  1.749849
        one       two     three
a  0.437957  0.100567 -1.568301
b       NaN       NaN       NaN
c  0.082134  1.475826  2.258137
d       NaN       NaN       NaN
e -1.009481  1.258612  0.714542
f -0.919802 -2.616542  0.396808
g       NaN       NaN       NaN
h -0.073464  1.252943  1.749849
        one       two     three
a  0.437957  0.100567 -1.568301
c  0.082134  1.475826  2.258137
e -1.009481  1.258612  0.714542
f -0.919802 -2.616542  0.396808
h -0.073464  1.252943  1.749849

In [ ]:
df=pd.read_csv("/content/2,1 dataset titanic.csv")
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
col=["Name","Ticket","Cabin"]
df=df.drop(col,axis=1)
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Fare         891 non-null    float64
 8   Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(2)
memory usage: 62.8+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df=df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Survived     712 non-null    int64
 2   Pclass       712 non-null    int64
 3   Sex          712 non-null    object
 4   Age          712 non-null    float64
 5   SibSp        712 non-null    int64
 6   Parch        712 non-null    int64
 7   Fare         712 non-null    float64
 8   Embarked     712 non-null    object
dtypes: float64(2), int64(5), object(2)
memory usage: 55.6+ KB

In [ ]:
dummies=[]
cols=['Pclass','Sex','Embarked']
for col in cols:
  dummies.append(pd.get_dummies(df[col]))
print(df)

     PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    male  22.0      1      0   7.2500
1              2         1       1  female  38.0      1      0  71.2833
2              3         1       3  female  26.0      0      0   7.9250
3              4         1       1  female  35.0      1      0  53.1000
4              5         0       3    male  35.0      0      0   8.0500
..           ...       ...     ...     ...   ...    ...    ...      ...
885          886         0       3  female  39.0      0      5  29.1250
886          887         0       2    male  27.0      0      0  13.0000
887          888         1       1  female  19.0      0      0  30.0000
889          890         1       1    male  26.0      0      0  30.0000
890          891         0       3    male  32.0      0      0   7.7500

    Embarked
0          S
1          C
2          S
3          S
4          S
..       ...
885        Q
886        S
887        S
889        C
890        Q

[712 rows x 9 columns]

In [ ]:
titanic_dummies=pd.concat(dummies,axis=1)
print(df)

     PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    male  22.0      1      0   7.2500
1              2         1       1  female  38.0      1      0  71.2833
2              3         1       3  female  26.0      0      0   7.9250
3              4         1       1  female  35.0      1      0  53.1000
4              5         0       3    male  35.0      0      0   8.0500
..           ...       ...     ...     ...   ...    ...    ...      ...
885          886         0       3  female  39.0      0      5  29.1250
886          887         0       2    male  27.0      0      0  13.0000
887          888         1       1  female  19.0      0      0  30.0000
889          890         1       1    male  26.0      0      0  30.0000
890          891         0       3    male  32.0      0      0   7.7500

    Embarked
0          S
1          C
2          S
3          S
4          S
..       ...
885        Q
886        S
887        S
889        C
890        Q

[712 rows x 9 columns]

In [ ]:
titanic_dummies=pd.concat(dummies,axis=1)
df=pd.concat((df,titanic_dummies),axis=1)

NameError: name 'pd' is not defined

In [ ]:
df=df.drop(df[["Pclass","Sex","Embarked"]],axis=1)

In [ ]:
df["age"]=df["Age"].interpolate()
print(df)

     PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    male  22.0      1      0   7.2500
1              2         1       1  female  38.0      1      0  71.2833
2              3         1       3  female  26.0      0      0   7.9250
3              4         1       1  female  35.0      1      0  53.1000
4              5         0       3    male  35.0      0      0   8.0500
..           ...       ...     ...     ...   ...    ...    ...      ...
885          886         0       3  female  39.0      0      5  29.1250
886          887         0       2    male  27.0      0      0  13.0000
887          888         1       1  female  19.0      0      0  30.0000
889          890         1       1    male  26.0      0      0  30.0000
890          891         0       3    male  32.0      0      0   7.7500

    Embarked   age
0          S  22.0
1          C  38.0
2          S  26.0
3          S  35.0
4          S  35.0
..       ...   ...
885        Q  39.0
886        S  27.0
887        S  19.0
889        C  26.0
890        Q  32.0

[712 rows x 10 columns]

In [ ]:
#y=(x-min)/(max-min)

from sklearn.preprocessing import MinMaxScaler
data=[[-1,2],[-0.5,6],[0,10],[1,18]]
scaler=MinMaxScaler()
print(scaler.fit(data))
print("----------")
MinMaxScaler()

MinMaxScaler()
----------

MinMaxScaler()

In [ ]:
from numpy import asarray
from sklearn.preprocessing import StandardScaler
data=asarray([[100,0.001],[8,0.05],[88,0.07],[4,0.1]])
print(data)
scalar=StandardScaler()
scaled=scaler.fit_transform(data)
print(scaled)

[[1.0e+02 1.0e-03]
 [8.0e+00 5.0e-02]
 [8.8e+01 7.0e-02]
 [4.0e+00 1.0e-01]]
[[1.         0.        ]
 [0.04166667 0.49494949]
 [0.875      0.6969697 ]
 [0.         1.        ]]